### ISSUE TITLE
Trying to spin this up, feels like I am connecting but then;  There are no remote procedure calls active on this thread. 

### ISSUE THREAD

**Issue by 10GeekJames** [AviNessimian/maui-blazor-app#1]
blazor.webview.js:1 
        
       System.Runtime.InteropServices.COMException (0x800706BD): There are no remote procedure calls active on this thread. (0x800706BD)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Security.Authentication.Web.IWebAuthenticationBrokerStaticsMethods.AuthenticateAsync(IObjectReference _obj, WebAuthenticationOptions options, Uri requestUri, Uri callbackUri)
   at Windows.Security.Authentication.Web.WebAuthenticationBroker.AuthenticateAsync(WebAuthenticationOptions options, Uri requestUri, Uri callbackUri)
   at Microsoft.Maui.Authentication.WebAuthenticatorImplementation.AuthenticateAsync(WebAuthenticatorOptions webAuthenticatorOptions)
   at MobileApp.Presentation.Auth.WebAuthenticatorBrowser.InvokeAsync(BrowserOptions options, CancellationToken cancellationToken)
   at MobileApp.Presentation.Auth.AuthService.HandleError(Result result)
   at MobileApp.Presentation.Auth.AuthService.Login()
   at MobileApp.Presentation.Main.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by AviNessimian** [comment]
Thank you for bringing this issue to our attention. 
We apologize for any inconvenience caused. 
We have tested the sample on an Android environment only, 

In windows enviromnet is a bug in the Windows App SDK and is being tracked at : [microsoft/WindowsAppSDK#441](https://github.com/microsoft/WindowsAppSDK/issues/441), you could follow the progress.
